version: '3'

services:
  client:
    container_name: phorkit-storybook
    build:
      context: ./
      dockerfile: ./.docker/storybook/Dockerfile
    image: phorkit-storybook
    env_file:
      - .env
    ports:
      - ${PUBLIC_STORYBOOK_PORT}:80
    networks:
      - phorknet

networks:
  phorknet:
    driver: bridge
